// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"TMMoveEx","status":true,"description":"壁衝突音やリージョンによる通行設定などの機能を追加します。","parameters":{"passableRegionId":"251","dontPassRegionId":"252","seKnockWall":"<name:Blow1><volume:90><pitch:100>","knockWallPan":"75","knockWallInterval":"30","turnKeyCode":"83"}},
{"name":"BootOpeningDemo","status":true,"description":"タイトル画面を出す前にオープニングデモから開始します","parameters":{"firstMapId":"1","startX":"0","startY":"0"}},
{"name":"TitleCommandPosition","status":true,"description":"タイトルコマンドウィンドウの位置を変更します。","parameters":{"Offset X":"0","Offset Y":"80","Width":"250","Background":"2"}}
];
